-- =============================================================================
-- NIA — Canonical categories (reference)
-- Categories are an application-level enum stored as `articles.category` (TEXT).
-- There is no separate categories table by design (keeps the schema minimal).
-- The backend CategoryMapper maps each provider's categories onto this list.
-- Keep this in sync with NIA_INGEST_CATEGORIES and the frontend category list.
-- =============================================================================
--   technology
--   business
--   world
--   india
--   science
--   sports
--   health
--   entertainment
--   politics
-- No rows to insert; this file documents the canonical set.
